###
GET http://localhost:8080/hello

###
GET http://James%20Bond:secret@localhost:8080/hello

###
POST http://localhost:8080/register
Content-Type: application/json

{
  "name": "James Bond",
  "password": "secret"
}

###
GET http://James%20Bond:secret@localhost:8080/hello

###
GET http://localhost:8080/hello
